[tools]
act = "0.2.75"
age = "1.2.1"
go = "1.24.0"
gotestsum = "1.12.0"
node = "22.14.0"
pnpm = "10.5.2"
sops = "3.9.4"
usage = "2.0.5"

[env]
APP_ENV = "local"
VITE_ENCORE_ENVIRONMENT = { value = "{{env.APP_ENV}}" }
_.file = ".env.secrets.json"

[tasks."gen:client:local"]
description = "Build Typescript client (Local)"
run = "encore gen client goauth-5g62 --output=./developer_area/frontend/src/lib/client.ts --env=local"

[tasks."build:backend"]
description = "Build Backend Docker images"
run = "encore build docker goauth"

[tasks."test:backend"]
description = "Run Backend tests"
run = "gotestsum --raw-command -- encore test ./... -json"

[tasks."test:watch:backend"]
description = "Run Backend tests in watch mode"
run = "gotestsum --watch --raw-command -- encore test ./... -json"

[tasks."test:frontend"]
description = "Run Frontend tests"
run = "pnpm --prefix developer_area/frontend exec playwright test --ui"

[tasks."test:frontend:headless"]
description = "Run Frontend tests"
run = "pnpm --prefix developer_area/frontend exec playwright test"

[tasks."ci:push"]
description = "Simulate a push on the CI"
run = "act --var ACTIONS_RUNTIME_TOKEN=foobar -s ENCORE_AUTH_KEY={{env.ENCORE_AUTH_KEY}} push"

[tasks."ci:push:frontend"]
description = "Simulate a push on the CI (Frontend)"
run = "act --var ACTIONS_RUNTIME_TOKEN=foobar -s ENCORE_AUTH_KEY={{env.ENCORE_AUTH_KEY}} -W .github/workflows/frontend.yaml push"

[tasks."ci:push:backend"]
description = "Simulate a push on the CI (Backend)"
run = "act --var ACTIONS_RUNTIME_TOKEN=foobar -s ENCORE_AUTH_KEY=\"{{env.ENCORE_AUTH_KEY}}\" -W .github/workflows/backend.yaml push"

[tasks."pc:up"]
description = "Start all the services with Process Compose"
run = "process-compose up -D"

[tasks."pc:down"]
description = "Stop all Process Compose services"
run = "process-compose down"

[tasks."pc:ui"]
description = "Show Process Compose UI"
run = "process-compose attach"

[tasks."pc:logs:backend"]
description = "Show Process Compose Backend logs"
run = "process-compose process logs test-backend -f"

[tasks."run:backend"]
description = "Run Backend"
run = "encore run"

[tasks."run:frontend"]
description = "Run Frontend"
run = "pnpm --prefix developer_area/frontend dev"
