version: "0.5"

processes:
  backend:
    command: mise run:backend
    availability:
      restart: "always"
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/health"
        port: 4000
      initial_delay_seconds: 5
      period_seconds: 300
    liveness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/health"
        port: 4000
      period_seconds: 300

  frontend:
    command: mise run:frontend
    availability:
      restart: "always"
    readiness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/signup"
        port: 5173
      initial_delay_seconds: 5
      period_seconds: 300
    liveness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/signup"
        port: 5173
      period_seconds: 300
    depends_on:
      backend:
        condition: process_healthy

  test-backend:
    command: mise test:backend

  test-frontend:
    command: mise test:frontend
    depends_on:
      frontend:
        condition: process_healthy
