// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              int64
	Email           string
	HashedPassword  string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	EmailVerifiedAt pgtype.Timestamp
}
