// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const byEmail = `-- name: ByEmail :one
select id, email, hashed_password, created_at, updated_at, email_verified_at FROM accounts where email = $1
`

func (q *Queries) ByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, byEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const byID = `-- name: ByID :one
select id, email, hashed_password, created_at, updated_at, email_verified_at FROM accounts where id = $1
`

func (q *Queries) ByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, byID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (email, hashed_password)
VALUES ($1, $2)
RETURNING id, email, hashed_password, created_at, updated_at, email_verified_at
`

type InsertAccountParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount, arg.Email, arg.HashedPassword)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, email, hashed_password, created_at, updated_at, email_verified_at FROM accounts
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailVerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE accounts
set email_verified_at = CURRENT_TIMESTAMP
WHERE email_verified_at is NULL and id = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, verifyEmail, id)
	return err
}
