name: Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Encore CLI script
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: bash install.sh

      - name: Log in to Encore
        run: |
          /home/runner/.encore/bin/encore auth login --auth-key="${{ secrets.ENCORE_AUTH_KEY }}"

      - name: Run tests
        run: /home/runner/.encore/bin/encore test ./...
